services:
  - type: web
    name: badminton-booker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 60 --workers 2
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
